# ====================================================================================================
#   로컬 개발 환경
# ====================================================================================================
spring:
  config:
    activate:
      on-profile: dev

  # 데이터베이스 구성 설정
  datasource:
    url: jdbc:h2:${JDBC_DB};${JDBC_OPTIONS}
    username: ${JDBC_USER}
    password: ${JDBC_PASSWORD}
    driver-class-name: org.h2.Driver

  # SQL 초기화 설정
  sql:
    init:
      # SQL 스크립트 초기화 : 내장 데이터베이스일 경우 스크립트 실행
      mode: EMBEDDED
      schema-locations: classpath:db/schema.sql

  # JSON 데이터 변환 규칙
  jackson:
    deserialization:
      # 정의되지 않은 필드 유입시 예외 발생
      fail-on-unknown-properties: true

  # 타임리프 캐시 및 경로 설정
  thymeleaf:
    # 브라우저의 새로고침을 통해 화면의 변경 이력 적용을 위한 뷰 템플릿 경로 설정
    prefix: file:src/main/resources/templates/
    cache: false

  # 정적 리소스 경로 설정
  web:
    resources:
      static-locations: file:src/main/resources/static/


# 서버 포트 번호 설정
server:
  port: 80


# 로깅
logging:
  file:
    path: ${LOG_PATH:./logs}
  level:
    root: info