# ====================================================================================================
#   운영 환경
# ====================================================================================================
spring:
  config:
    activate:
      on-profile: prod

  # 데이터베이스 구성 설정
  datasource:
    url: jdbc:mariadb://${JDBC_SERVER_ADDRESS:localhost}:${JDBC_SERVER_PORT:3306}/${JDBC_DB}?${JDBC_OPTIONS}
    username: ${JDBC_USER}
    password: ${JDBC_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000

  # JSON 데이터 변환 처리
  jackson:
    deserialization:
      # 정의되지 않은 필드 유입시 예외 발생 허용 비활성화
      fail-on-unknown-properties: false

  # 타임리프 경로 변경 및 캐싱 활성화
  thymeleaf:
    prefix: classpath:/templates/
    cache: true

  # 정적 리소스 경로 변경 및 캐싱 기간 설정
  web:
    resources:
      static-locations: classpath:/static/
      cache:
        period: 36000

# 서버 포트 변경
server:
  port: 8588

# 로깅
logging:
  file:
    path: ${LOG_PATH}
  level:
    root: info

